server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: 1Z_TnptJooFkkPoFvLt7
            client-secret: JveMcf1LiX
            scope:
              - nickname
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  datasource:
    url: jdbc:postgresql://localhost:5432/plan-nest
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: cache-server
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.boot.actuate: DEBUG
    org.springframework.cache: trace # Redis 사용에 대한 로그가 조회되도록 설정