server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id:
            client-secret:
            redirect-uri:
            client-name: Naver
            authorization-grant-type: authorization_code
            scope:
              - name
          provider:
            naver:
              authorization_uri: https://nid.naver.com/oauth2.0/authorize
              token_uri: https://nid.naver.com/oauth2.0/token
              user-info-uri: https://openapi.naver.com/v1/nid/me
              user_name_attribute: response
  datasource:
    url: jdbc:postgresql://localhost:5432/plan-nest
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.boot.actuate: DEBUG